CREATE TABLE students(id serial, name text, quality1 text, quality2 text);
INSERT INTO students(id, name, quality1, quality2) VALUES
(1,'Bennie Hodkiewicz','brave','cunning'),
(2,'Octavia Huels','lazy','hopeless'),
(3,'Elta Okuneva','materialistic','generous'),
(4,'Mr. Destin Murazik','generous','hopeless'),
(5,'Shaniya Hane','happy','hyper'),
(6,'Abbie Ratke','happy','sad'),
(7,'Mrs. Michelle Lubowitz','generous','lazy'),
(8,'Kassandra Emmerich PhD','flighty','hufflepuff'),
(9,'Mallie Kautzer','shy','sad'),
(10,'Nichole Swaniawski','daring','materialistic'),
(11,'Modesta Ritchie','lazy','flighty'),
(12,'Alena Runte','daring','shy'),
(13,'Dr. Aurelia Wisozk','studious','hyper'),
(14,'Aubrey Larkin I','hufflepuff','cowardly'),
(15,'Miss Jarrell Zulauf','imaginative','sad'),
(16,'Craig Stroman DDS','evil','imaginative'),
(17,'Erica Weissnat','hyper','daring'),
(18,'Miss Clementina Kihn','sad','hyper'),
(19,'Christopher Hilpert','complacent','cowardly'),
(20,'Mrs. Aileen Stark','happy','hopeless'),
(21,'Nikolas Davis','daring','complacent'),
(22,'Claud OKeefe','courageous','materialistic'),
(23,'Claudie Fahey DVM','hufflepuff','imaginative'),
(24,'Berenice Casper','cowardly','courageous'),
(25,'Rolando Olson','imaginative','naive'),
(26,'Wilber Stark','hyper','materialistic'),
(27,'Geovanni Stamm','imaginative','cowardly'),
(28,'Lennie Hodkiewicz','hufflepuff','naive'),
(29,'Destinee Cummings','hufflepuff','flighty'),
(30,'Liliane Cruickshank','brave','lonely'),
(31,'Ms. Katherine Boyer','studious','courageous'),
(32,'Freddie Torp','brave','shy'),
(33,'Mr. Laury Bins','courageous','devious'),
(34,'Brooke Bechtelar','daring','materialistic'),
(35,'Dr. Shana Schuster','imaginative','evil'),
(36,'Oral Gleichner','lazy','intelligent'),
(37,'Sheridan Reynolds','hyper','complacent'),
(38,'Ms. Evelyn Keebler','generous','cunning'),
(39,'Junior Stark','complacent','flighty'),
(40,'Duane Fahey Sr.','materialistic','daring'),
(41,'Ophelia Hilll MD','daring','courageous'),
(42,'Hobart Streich','shy','generous'),
(43,'Stanley Mohr','daring','lonely'),
(44,'Deon Stokes','imaginative','complacent'),
(45,'Garth Schneider','hyper','courageous'),
(46,'Dejon Waters DDS','materialistic','lazy'),
(47,'Miss Elva Feeney','imaginative','naive'),
(48,'Regan Howe','naive','intelligent'),
(49,'Marc Homenick','hyper','complacent'),
(50,'Lenore Trantow','materialistic','evil'),
(51,'Emmet Cruickshank','flighty','shy'),
(52,'Ben Tremblay','imaginative','evil'),
(53,'Madie Bergnaum V','hyper','complacent'),
(54,'Eladio Wehner','brave','lazy'),
(55,'Omer Conroy III','daring','naive'),
(56,'Helen Lind','hufflepuff','courageous'),
(57,'Mrs. Johnathon Hettinger','studious','evil'),
(58,'Ms. Ardella Rosenbaum','naive','complacent'),
(59,'Shany Kohler','flighty','imaginative'),
(60,'Abbey Spinka','lazy','cunning'),
(61,'Haylee Powlowski','generous','happy'),
(62,'Rosario Schulist PhD','happy','courageous'),
(63,'Dovie Torphy','sad','happy'),
(64,'Otis Boyer','happy','sad'),
(65,'Johann Brekke','complacent','materialistic'),
(66,'Ernest Willms','materialistic','hufflepuff'),
(67,'Terrell Oberbrunner','complacent','happy'),
(68,'Ottis Romaguera','evil','devious'),
(69,'Alysha Volkman','lazy','hufflepuff'),
(70,'Leonardo Aufderhar','cowardly','generous'),
(71,'Carolyne Leffler II','evil','complacent'),
(72,'Mrs. Eve Carter','hyper','sad'),
(73,'Loren Steuber','cowardly','sad'),
(74,'Arianna Wiegand','courageous','daring'),
(75,'Miss Sid Little','studious','happy'),
(76,'Hermina Rowe','generous','happy'),
(77,'Maudie Keebler','sad','devious'),
(78,'Julia Ferry','lonely','sad'),
(79,'Kristofer Bartoletti','studious','naive'),
(80,'Amalia Zboncak','happy','evil'),
(81,'Jo Bernier','evil','daring'),
(82,'Zola Ernser DDS','complacent','materialistic'),
(83,'Santina Larson','naive','complacent'),
(84,'Oda Pfeffer','studious','hyper'),
(85,'Sidney Koch','daring','shy'),
(86,'Mrs. Adeline Ryan','complacent','naive'),
(87,'Haylee Kautzer','evil','materialistic'),
(88,'Emanuel Bins','generous','flighty'),
(89,'Gerhard Ziemann','shy','hyper'),
(90,'Saul Rolfson','complacent','courageous'),
(91,'Billy Haag','happy','devious'),
(92,'Evie Beier PhD','evil','lazy'),
(93,'Gudrun Mitchell','devious','naive'),
(94,'Pierce Batz V','lonely','sad'),
(95,'Walton Shanahan','devious','cowardly'),
(96,'Miss Patience Gutkowski','happy','materialistic'),
(97,'Rozella Johnson','evil','cowardly'),
(98,'Dr. Rod Conn','brave','courageous'),
(99,'Trevor Kilback','cowardly','cowardly'),
(100,'Raheem Grady','complacent','hyper');